/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.epam.training.order.api;

import com.epam.training.order.apimodel.ErrorModel;
import com.epam.training.order.apimodel.OrderAndPackageModel;
import com.epam.training.order.apimodel.OrderModel;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-09-19T17:50:50.966293+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "Order", description = "the Order API")
public interface OrderApi {

    /**
     * GET /api/v1/aggregatedorders/{id}
     * Returns the order and the package associated with the provided id in path
     *
     * @param id The id of the queried order (required)
     * @return Normal response (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "getAggregatedOrder",
        description = "Returns the order and the package associated with the provided id in path",
        tags = { "Order" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Normal response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrderAndPackageModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/aggregatedorders/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<OrderAndPackageModel> getAggregatedOrder(
        @Parameter(name = "id", description = "The id of the queried order", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );


    /**
     * GET /api/v1/orders/{id}
     * Returns the order associated with the provided id in path
     *
     * @param id The id of the queried order (required)
     * @return Normal response (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "getOrder",
        description = "Returns the order associated with the provided id in path",
        tags = { "Order" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Normal response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrderModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/orders/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<OrderModel> getOrder(
        @Parameter(name = "id", description = "The id of the queried order", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );

}
