/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.epam.training.shipping.api;

import com.epam.training.shipping.apimodel.ErrorModel;
import com.epam.training.shipping.apimodel.PackageModel;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-09-19T16:46:48.576522300+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "Shipping", description = "the Shipping API")
public interface ShippingApi {

    /**
     * GET /api/v1/packages/{id}
     * Returns the package associated with the provided id in path
     *
     * @param id The id of the queried package (required)
     * @return Normal response (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "getPackage",
        description = "Returns the package associated with the provided id in path",
        tags = { "Shipping" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Normal response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PackageModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/packages/{id}",
        produces = "application/json"
    )
    
    ResponseEntity<PackageModel> getPackage(
        @Parameter(name = "id", description = "The id of the queried package", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    );

}
